[project]
name = "mlops-flow-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "mlflow>=3.2.0",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pendulum>=3.1.0",
    "scikit-learn>=1.7.1",
]
