FROM python:3.11-slim

# Tools useful for debugging/healthchecks
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl net-tools iproute2 procps \
 && rm -rf /var/lib/apt/lists/*

# MLflow + Postgres driver
RUN pip install --no-cache-dir mlflow psycopg2-binary

WORKDIR /srv
EXPOSE 5000

# Ensure the artifact dir exists (server writes here when proxying)
RUN mkdir -p /mlartifacts

# ENTRYPOINT = executable; CMD = default args
ENTRYPOINT ["mlflow", "server"]
CMD [
  "--host", "0.0.0.0",
  "--port", "5000",
  "--backend-store-uri", "postgresql+psycopg2://airflow:airflow@postgres:5432/mlflow",
  "--serve-artifacts",
  "--artifacts-destination", "/mlartifacts"
]
